import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/components/Navbar";
import Script from 'next/script'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

<Script
  src="https://cdn.jsdelivr.net/npm/@mediapipe/pose"
  strategy="beforeInteractive"
/>
<Script
  src="https://cdn.jsdelivr.net/npm/@mediapipe/camera_utils"
  strategy="beforeInteractive"
/>
<Script
  src="https://cdn.jsdelivr.net/npm/@mediapipe/drawing_utils"
  strategy="beforeInteractive"
/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        <Navbar/>
        {children}
      </body>
    </html>
  );
}
